### PR TITLE
Adding the "Unzip file" action

### PR DESCRIPTION
**Pull request by tylermumford**
This update creates a new action in Belvedere that unzips the matched files.

It uses the already-bundled `7za.exe` to do this. The critical line of code is:

```
actions.ahk - line 224
RunWait, %A_ScriptDir%\resources\7za.exe x -o"%directory%\%name%" "%directory%\%fullname%",,hide UseErrorLevel
```

Because this is a plain and simple call to 7za, it can extract any files that 7za can. This is essentially all standard archives except .exe files.

By the way, @adampash, you certainly wrote Belvedere to be easily modified with new actions. Thank you.

This addresses issues #36 and #48, I believe.

(No, I don't sleep. I code. It's more meaningful.)

And I'm curious: who's managing Belvedere right now? The only activity in the past few months is on mshorts's fork, yet the Belvedere post on Lifehacker was just updated.

### CODE REVIEW

**Comment by mshorts** [comment]
Great contribution, thanks!  My only criticism is that it doesn't really follow the convention that is used by the compress option that's already implemented (a check box).  I'd hate to see one option be a simple check, while the other takes up a new rule with an action.  Maybe there is a more slick way of doing it with a radio button option instead of a check box for zip/unzip?

The past few releases have been managed by me, and I've simply been in contact with Adam when a new release is ready, and he puts out a new article on Lifehacker.  I'm happy to continue this way and help manage things if you want to help out and tackle some of the open items on the issues list.

**Comment by tylermumford** [comment]
Hm. That's a good point. I considered it to be more of an action, since it only applies to certain file types, but we don't want the feature to <del>break conventions</del> <ins>be inconsistent</ins> (and I agree that it currently <del>does</del> <ins>is</ins>).

I think we'll need a bit of Deep Thought and/or a Brain Blast regarding how to best implement this.

<ins>Conventions can be okay to break when the result is an improvement that is still easy to use, but inconsistency is pretty much always a bad thing.</ins>

**Comment by tylermumford** [comment]
### Initial thoughts:

I can think of two goals when wanting to unzip a file:
1. Extract the files within, so that other rules can act on them.
2. Put the file somewhere else, and then extract it.

Whatever the chosen solution, it should provide for these two cases.

---

The more I think about it, the more I believe the action should look something like this:

```
Move/copy file > to folder: [_________] > Overwrite, (Direct || Compressed | Extracted)
```

This is powerful enough to cover both cases, yet simple enough that it only adds one more control. (And yes, I think this is what you were suggesting in the first place. Molehill -> Mountain.)

The catch is that if a user knows he wants to unzip a file, the first place he'll look will not be under the "Move file" action, it will be for an "Unzip file" action. Or so I would think. So the most intuitive approach would be `Unzip file > to this folder > Overwrite`. But we would have to combine both of these methods to cover both use cases and still be intuitive.

Still working on something better.

**Comment by HyShai** [comment]
Can you please add this to an (updated) exe ? Thank you so much!

**Comment by pc1oad1etter** [comment]
What changes need to happen to get this implemented?

"My only criticism is that it doesn't really follow the convention that is used by the compress option that's already implemented (a check box)"
Where is a there a compress checkbox currently?

I'd love to use this -- is there a string to put in the custom action box to make this work manually?

**Pull request closed without merging**
